sei22-project/bobby

app/controllers/games_controller.rb
app/controllers/requests_controller.rb
app/helpers/requests_helper.rb
app/models/game.rb
app/models/request.rb
app/models/user.rb
app/views/games/show.html.erb
app/views/requests/_form.html.erb
config/routes.rb
test/controllers/requests_controller_test.rb
test/fixtures/requests.yml
test/models/request_test.rb
test/system/requests_test.rb

Setup requests controller, form partial for submitting a join game request, integrated with games controller and game show view

Requests Setup

---

app/controllers/games_controller.rb
app/controllers/requests_controller.rb
app/views/games/show.html.erb
app/views/requests/_form.html.erb
app/views/requests/_host_request.html.erb
config/routes.rb

Join Request / Host Approve Reject / Request Pending Approved Rejected

Basic game request logic

---

app/controllers/categories_controller.rb
app/javascript/packs/category.js
app/views/categories/index.html.erb
config/routes.rb

Created layout for categories#index. Commencing Ajax request to sort games

Categories layout

---

app/controllers/games_controller.rb
app/views/games/show.html.erb

Conditional rendering of chat room link in game#show view

Chat Room links from Game

---

app/controllers/categories_controller.rb
app/controllers/games_controller.rb
app/controllers/home_controller.rb
app/controllers/rooms_controller.rb
app/controllers/users_controller.rb
app/views/layouts/_navbar.html.erb
app/views/layouts/application.html.erb
config/routes.rb

Add navbar partial and links to controllers (for dev purposes, for prod will want to re-think links)

Navbar (Dev)

---

app/javascript/stylesheets/global.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb

F login view

---

app/controllers/messages_controller.rb
app/javascript/channels/room_channel.js
app/jobs/send_message_job.rb
app/views/messages/_message.html.erb
app/views/messages/_other-message.html.erb
app/views/rooms/show.html.erb

Remove subscription when user leaves room + conditionally render class on message for styling purposes

Optimise Chatroom

---

app/views/messages/_message.html.erb
app/views/messages/_other-message.html.erb
app/views/rooms/show.html.erb

Add basic tailwind classes to chat room

style: Add basic tailwind classes (message, user, timestamp alignment)

---

app/controllers/rooms_controller.rb
app/views/messages/_form.html.erb
app/views/rooms/show.html.erb

Add sidebar with chatroom participants / host

Chatroom participants

---

app/javascript/packs/game.js
app/views/games/new.html.erb

Newgames design

---

app/views/games/new.html.erb

Completed design for new game form

New game complete

---

app/channels/activity_channel.rb
app/channels/application_cable/connection.rb
app/controllers/application_controller.rb
app/javascript/channels/activity_channel.js
app/views/rooms/show.html.erb
db/migrate/20200522121629_add_online_to_users.rb
db/schema.rb
test/channels/activity_channel_test.rb

Add Activity Channel, online column to User table, room show online/offline users by opacity

Activity Channel Setup

---

Gemfile
Gemfile.lock
app/assets/stylesheets/notifications.scss
app/controllers/notifications/notifications_controller.rb
app/models/notification.rb
app/models/request.rb
app/views/layouts/application.html.erb
app/views/notifications/_join_request.html.erb
app/views/notifications/notifications/_notification.html.erb
app/views/notifications/notifications/index.html.erb
config/initializers/notifications.rb
config/routes.rb
db/migrate/20200522191658_create_notifications.notifications.rb
db/schema.rb

Inst notifications gem
Generate controllers, views, model, initializers
Run migration
Set up create notification for join requests

Notifications setup

---

app/controllers/games_controller.rb
app/helpers/application_helper.rb
app/javascript/stylesheets/global.scss
app/models/game.rb
app/views/games/new.html.erb
config/routes.rb

completed validation and refined styling for games#new

New game validation complete

---

app/controllers/notifications/notifications_controller.rb
app/controllers/requests_controller.rb
app/javascript/channels/activity_channel.js
app/models/request.rb
app/views/layouts/_notification_message.html.erb
app/views/layouts/application.html.erb

Broadcast and render notifications on DOM

Notifications Channel

---

Gemfile
Gemfile.lock
app/controllers/categories_controller.rb
app/views/categories/_card.html.erb
app/views/categories/index.html.erb
db/seeds.rb

Categories pagination complete

Categories pagination

---

app/assets/stylesheets/notifications.scss
app/controllers/requests_controller.rb
app/javascript/channels/activity_channel.js
app/models/request.rb
app/views/layouts/application.html.erb
app/views/notifications/_join_request.html.erb
app/views/notifications/_kick_user.html.erb
app/views/notifications/_left_game.html.erb
app/views/notifications/_update_request.html.erb
app/views/notifications/_withdraw_request.html.erb
app/views/notifications/notifications/index.html.erb

Basic styles, check for consistency with other views

Notifications index styles

---

app/controllers/categories_controller.rb

All sorted games will not show games that current user is a host

Exclude games

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css
app/controllers/users_controller.rb
app/javascript/stylesheets/application.scss
app/javascript/stylesheets/gravatar.scss
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/show_profile.html.erb
config/routes.rb
db/migrate/20200524084452_create_active_storage_tables.active_storage.rb
db/schema.rb

Add basic user profile:
- Name
- Upload profile picture (Active Storage / Gravatar)

User profile

---

app/views/layouts/application.html.erb

fix: Error on application (current_user.avatar) when user not signed in
